app = "skylight-web-service"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
ROLLBAR_ENVIRONMENT = "production"
# ROLLBAR_ACCESS_TOKEN is set as a fly secret

[experimental]
allowed_public_ports = []
auto_rollback = true

[metrics]
port = 9090
path = "/metrics"

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
