name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-22.04
    environment: fly.io
    concurrency: fly.io
    url: https://fly.io/apps/skylight-web-service
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@1.3

      - name: Run
        run: flyctl deploy --remote-only
